package com.prafullkumar.posedetector.staticImage.domain.models

import com.google.mlkit.vision.pose.Pose
import com.google.mlkit.vision.pose.PoseLandmark


data class PoseDetails(
    val leftShoulder: PoseLandmark?,
    val rightShoulder: PoseLandmark?,
    val leftElbow: PoseLandmark?,
    val rightElbow: PoseLandmark?,
    val leftWrist: PoseLandmark?,
    val rightWrist: PoseLandmark?,
    val leftHip: PoseLandmark?,
    val rightHip: PoseLandmark?,
    val leftKnee: PoseLandmark?,
    val rightKnee: PoseLandmark?,
    val leftAnkle: PoseLandmark?,
    val rightAnkle: PoseLandmark?,
    val leftPinky: PoseLandmark?,
    val rightPinky: PoseLandmark?,
    val leftIndex: PoseLandmark?,
    val rightIndex: PoseLandmark?,
    val leftThumb: PoseLandmark?,
    val rightThumb: PoseLandmark?,
    val leftHeel: PoseLandmark?,
    val rightHeel: PoseLandmark?,
    val leftFootIndex: PoseLandmark?,
    val rightFootIndex: PoseLandmark?,
    val nose: PoseLandmark?,
    val leftEyeInner: PoseLandmark?,
    val leftEye: PoseLandmark?,
    val leftEyeOuter: PoseLandmark?,
    val rightEyeInner: PoseLandmark?,
    val rightEye: PoseLandmark?,
    val rightEyeOuter: PoseLandmark?,
    val leftEar: PoseLandmark?,
    val rightEar: PoseLandmark?,
    val leftMouth: PoseLandmark?,
    val rightMouth: PoseLandmark?
)
fun Pose.toPoseDetails() = PoseDetails(
    leftShoulder = getPoseLandmark(PoseLandmark.LEFT_SHOULDER),
    rightShoulder = getPoseLandmark(PoseLandmark.RIGHT_SHOULDER),
    leftElbow = getPoseLandmark(PoseLandmark.LEFT_ELBOW),
    rightElbow = getPoseLandmark(PoseLandmark.RIGHT_ELBOW),
    leftWrist = getPoseLandmark(PoseLandmark.LEFT_WRIST),
    rightWrist = getPoseLandmark(PoseLandmark.RIGHT_WRIST),
    leftHip = getPoseLandmark(PoseLandmark.LEFT_HIP),
    rightHip = getPoseLandmark(PoseLandmark.RIGHT_HIP),
    leftKnee = getPoseLandmark(PoseLandmark.LEFT_KNEE),
    rightKnee = getPoseLandmark(PoseLandmark.RIGHT_KNEE),
    leftAnkle = getPoseLandmark(PoseLandmark.LEFT_ANKLE),
    rightAnkle = getPoseLandmark(PoseLandmark.RIGHT_ANKLE),
    leftPinky = getPoseLandmark(PoseLandmark.LEFT_PINKY),
    rightPinky = getPoseLandmark(PoseLandmark.RIGHT_PINKY),
    leftIndex = getPoseLandmark(PoseLandmark.LEFT_INDEX),
    rightIndex = getPoseLandmark(PoseLandmark.RIGHT_INDEX),
    leftThumb = getPoseLandmark(PoseLandmark.LEFT_THUMB),
    rightThumb = getPoseLandmark(PoseLandmark.RIGHT_THUMB),
    leftHeel = getPoseLandmark(PoseLandmark.LEFT_HEEL),
    rightHeel = getPoseLandmark(PoseLandmark.RIGHT_HEEL),
    leftFootIndex = getPoseLandmark(PoseLandmark.LEFT_FOOT_INDEX),
    rightFootIndex = getPoseLandmark(PoseLandmark.RIGHT_FOOT_INDEX),
    nose = getPoseLandmark(PoseLandmark.NOSE),
    leftEyeInner = getPoseLandmark(PoseLandmark.LEFT_EYE_INNER),
    leftEye = getPoseLandmark(PoseLandmark.LEFT_EYE),
    leftEyeOuter = getPoseLandmark(PoseLandmark.LEFT_EYE_OUTER),
    rightEyeInner = getPoseLandmark(PoseLandmark.RIGHT_EYE_INNER),
    rightEye = getPoseLandmark(PoseLandmark.RIGHT_EYE),
    rightEyeOuter = getPoseLandmark(PoseLandmark.RIGHT_EYE_OUTER),
    leftEar = getPoseLandmark(PoseLandmark.LEFT_EAR),
    rightEar = getPoseLandmark(PoseLandmark.RIGHT_EAR),
    leftMouth = getPoseLandmark(PoseLandmark.LEFT_MOUTH),
    rightMouth = getPoseLandmark(PoseLandmark.RIGHT_MOUTH)
)